import ogManifest from "@/data-helpers/og/manifest.json";
import { absoluteOgImageUrl, getSiteOrigin } from "@/config/site-origin";
import {
  lookupOgImage,
  ogCollectionKey,
  ogDocKey,
  ogPageKey,
  type OgManifest
} from "@/statics-generator/og-manifest";
import { siteConfig } from "@/config/site";
import { withLocale } from "@/locales";
import { AvailableLanguages, Languages } from "@/types";
import type { Metadata } from "next";

export type MetadataType = "page" | "doc" | "collection" | "icon";

export const customMetadata = (
  lang: Languages,
  type: MetadataType,
  path: string,
  title?: string,
  description?: string,
  collectionId?: string,
  iconId?: string
): Metadata => {
  const { name, defaultLocale } = siteConfig;
  const origin = getSiteOrigin();
  const brand = withLocale(lang).config("brand");
  const pageTitle =
    `${title ?? name}` +
    (title?.endsWith(siteConfig.name) ? "" : ` | ${name} | ${brand["title-suffix"]}`);
  const pageDescription = description ?? brand.description;
  const imageUrl = getOpenGraphImage(lang, type, path, collectionId);
  const images = [
    {
      url: imageUrl.toString(),
      type: imageUrl.pathname.endsWith(".png") ? "image/png" : "image/jpeg",
      width: 1200,
      height: 630,
      alt: pageTitle
    }
  ];

  const localizedUrl = (language: Languages) => {
    if (type === "doc") {
      const doc = withLocale(language).doc(path);
      return new URL(`/${language}/docs/${doc.slug}/`, origin);
    }
    if (type === "collection" || type === "icon") {
      const url = new URL(`/${language}/icons/${collectionId}/`, origin);
      if (iconId) url.searchParams.set("icon", iconId);
      return url;
    }
    return new URL(`/${language}/${path ? `${path}/` : ""}`, origin);
  };

  const canonicalUrl = localizedUrl(lang);
  const languages = AvailableLanguages.reduce<Record<string, string>>(
    (items, language) => ({ ...items, [language]: localizedUrl(language).toString() }),
    {}
  );

  return {
    title: pageTitle,
    description: pageDescription,
    keywords: ["React", "React Native", "Tailwind", "rocketicons", "icons"],
    authors: [{ name, url: origin }],
    creator: siteConfig.companyName,
    openGraph: {
      type: "website",
      locale: lang || defaultLocale,
      url: canonicalUrl.toString(),
      title: pageTitle,
      description: pageDescription,
      siteName: name,
      images
    },
    twitter: {
      card: "summary_large_image",
      title: pageTitle,
      site: name,
      description: pageDescription,
      creator: "@therocketclimb",
      images
    },
    icons: {
      icon: "/favicon.ico",
      shortcut: "/favicon-16x16.png"
    },
    alternates: {
      canonical: canonicalUrl.toString(),
      languages
    },
    metadataBase: new URL(origin)
  };
};

/**
 * Resolves the build-time image generated by `statics-generator/og-images.ts`, using that
 * module's own key builders so generation and lookup cannot drift.
 *
 * Sampled builds (RI_GENERATE_ALL_ICONS unset) only render the first five collections, so a
 * miss is expected rather than exceptional and falls back to the static hero plate. Building
 * with `absoluteOgImageUrl` keeps the deployment base path, which a bare
 * `new URL("/img/...", origin)` would silently drop on a subfolder deploy, and lets preview
 * deployments point at their own images without moving canonical or hreflang off production.
 */
export const getOpenGraphImage = (
  lang: Languages,
  type: MetadataType,
  path: string,
  collectionId?: string
) => {
  const manifest = ogManifest as OgManifest;

  if (type === "collection" || type === "icon") {
    return absoluteOgImageUrl(
      lookupOgImage(manifest, "collections", ogCollectionKey(lang, collectionId ?? ""))
    );
  }

  if (type === "doc") {
    const slug = withLocale(lang).doc(path)?.slug ?? path;
    return absoluteOgImageUrl(lookupOgImage(manifest, "docs", ogDocKey(lang, slug)));
  }

  return absoluteOgImageUrl(lookupOgImage(manifest, "pages", ogPageKey(lang, path)));
};
