type serverSchema = {
  GOOGLE_ANALYTICS_ID: string | undefined;
  NEXT_PUBLIC_ALGOLIA_APPLICATION_ID: string;
  NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY_API_KEY: string;
  ALGOLIA_ADMIN_KEY: string;
  SKIP_BUILD_STATIC_GENERATION: boolean;
  NEXT_PUBLIC_PLAYGROUND_URL: string | undefined;
};

export const serverEnv = {
  GOOGLE_ANALYTICS_ID: process.env.NEXT_GOOGLE_ANALYTICS_ID,
  NEXT_PUBLIC_ALGOLIA_APPLICATION_ID: process.env.NEXT_PUBLIC_ALGOLIA_APPLICATION_ID ?? "",
  NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY_API_KEY:
    process.env.NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY_API_KEY ?? "",
  ALGOLIA_ADMIN_KEY: process.env.ALGOLIA_ADMIN_KEY ?? "",
  SKIP_BUILD_STATIC_GENERATION: process.env.SKIP_BUILD_STATIC_GENERATION === "true",
  NEXT_PUBLIC_PLAYGROUND_URL: process.env.NEXT_PUBLIC_PLAYGROUND_URL
} satisfies serverSchema;
