type serverSchema = {
  NEXT_PUBLIC_APP_URL: string;
  GOOGLE_ANALYTICS_ID: string;
  NEXT_PUBLIC_ALGOLIA_APPLICATION_ID: string;
  NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY_API_KEY: string;
  ALGOLIA_ADMIN_KEY: string;
  SKIP_BUILD_STATIC_GENERATION: boolean;
  NEXT_PUBLIC_PLAYGROUND_URL: string | undefined;
};

export const serverEnv = {
  NEXT_PUBLIC_APP_URL: String(process.env.NEXT_PUBLIC_APP_URL),
  GOOGLE_ANALYTICS_ID: String(process.env.NEXT_GOOGLE_ANALYTICS_ID),
  NEXT_PUBLIC_ALGOLIA_APPLICATION_ID: String(process.env.NEXT_PUBLIC_ALGOLIA_APPLICATION_ID),
  NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY_API_KEY: String(
    process.env.NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY_API_KEY
  ),
  ALGOLIA_ADMIN_KEY: String(process.env.ALGOLIA_ADMIN_KEY),
  SKIP_BUILD_STATIC_GENERATION: Boolean(process.env.SKIP_BUILD_STATIC_GENERATION),
  NEXT_PUBLIC_PLAYGROUND_URL: process.env.NEXT_PUBLIC_PLAYGROUND_URL
} satisfies serverSchema;
