import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, test } from "@jest/globals";

import { buildContextArtifacts, loadContextSource, validateContextSource } from "./core";
import type { ContextSourceIcon } from "./types";

const collections: Array<[string, number, number]> = [
  ["rc", 1, 1],
  ["ti", 237, 336],
  ["tfi", 300, 352],
  ["vsc", 632, 653],
  ["hi", 226, 460],
  ["hi2", 648, 972],
  ["im", 491, 491],
  ["gr", 628, 637],
  ["cg", 682, 704],
  ["io", 672, 696],
  ["fa", 1541, 1611],
  ["io5", 918, 1332],
  ["rx", 326, 332],
  ["ai", 647, 848],
  ["tb", 5124, 6184],
  ["lia", 1331, 1544],
  ["bi", 1030, 1634],
  ["bs", 1389, 2754],
  ["fa6", 2051, 2058],
  ["gi", 4037, 4040],
  ["md", 2192, 4341],
  ["pi", 7545, 9072],
  ["ri", 3185, 3188],
  ["si", 3458, 3458]
];

const sources = new Map(collections.map(([id]) => [id, loadContextSource(id)!]));

describe("reviewed collections reaching half of the catalog", () => {
  test.each(collections)(
    "%s has complete metadata bound to the current glyphs",
    (id, families, total) => {
      const source = sources.get(id)!;
      expect(source).toBeDefined();
      validateContextSource(source);
      expect(source.families).toHaveLength(families);
      const manifest = require(resolve(`../icons/${id}/manifest.js`)).manifest;
      const icons: ContextSourceIcon[] = Object.values(manifest.icons).map((value) => {
        const entry = value as { id: string; name: string; compName: string; variant: string };
        return {
          id: entry.id,
          name: entry.name,
          component: entry.compName,
          variant: entry.variant,
          iconTree: JSON.parse(
            readFileSync(resolve(`../generator/svgs/${id}/${entry.id}.json`), "utf8")
          ).iconTree
        };
      });
      const result = buildContextArtifacts(id, "test", icons, source);
      expect(result.index.coverage).toEqual({
        total,
        enriched: total,
        missing: 0,
        stale: 0,
        orphaned: 0,
        complete: true
      });
    }
  );

  const queries: Array<[string, string, string, string]> = [
    ["vsc", "agent", "coding agent", "agente de programação"],
    ["vsc", "git-stash-apply", "apply stash", "aplicar stash"],
    ["vsc", "git-stash-pop", "pop stash", "recuperar stash"],
    ["vsc", "copilot-error", "Copilot error", "erro do Copilot"],
    ["vsc", "chat-sparkle", "AI chat", "conversa com IA"],
    ["vsc", "mic-off", "mute microphone", "silenciar microfone"],
    ["vsc", "twitter", "X", "X"],
    ["gr", "genai", "generative AI", "IA generativa"],
    ["gr", "genaifill", "generate content", "gerar conteúdo"],
    ["rc", "rocket-icon", "icon library", "biblioteca de ícones"],
    ["ti", "trash", "delete", "excluir"],
    ["ti", "arrow-left", "previous item", "item anterior"],
    ["ti", "warning", "warning", "aviso"],
    ["ti", "social-github", "GitHub logo", "Logotipo do GitHub"],
    ["tfi", "support", "first aid", "primeiros socorros"],
    ["tfi", "cup", "award", "prêmio"],
    ["tfi", "server", "database", "banco de dados"],
    ["tfi", "google", "Google+ logo", "Logotipo do Google+"],
    ["vsc", "debug-step-into", "enter function", "entrar na função"],
    [
      "vsc",
      "debug-breakpoint-conditional-unverified",
      "pending debugger binding",
      "vínculo pendente no depurador"
    ],
    ["vsc", "library", "documentation", "documentação"],
    ["vsc", "error", "failure", "falha"],
    ["hi", "save", "persist changes", "guardar alterações"],
    ["hi", "volume-off", "mute", "silenciar"],
    ["hi", "exclamation", "warning", "aviso"],
    ["hi2", "home", "home page", "página inicial"],
    ["hi2", "magnifying-glass", "search", "busca"],
    ["hi2", "arrow-left", "previous item", "item anterior"],
    ["hi2", "trash", "delete", "excluir"],
    ["hi2", "arrow-left", "back", "voltar"],
    ["hi2", "bell", "notifications", "notificações"],
    ["hi2", "check-circle", "success", "sucesso"],
    ["hi2", "shopping-cart", "checkout", "finalizar compra"],
    ["hi2", "shield-check", "verified protection", "proteção verificada"],
    ["hi2", "mini-arrow-left", "previous item", "item anterior"],
    ["hi2", "document", "file", "arquivo"],
    ["hi2", "code-bracket", "developer tools", "ferramentas de desenvolvimento"],
    ["hi2", "map-pin", "location", "localização"],
    ["hi2", "face-smile", "reaction", "reação"],
    ["hi2", "server", "hosting", "hospedagem"],
    ["im", "tree", "organization chart", "organograma"],
    ["im", "power", "electricity", "eletricidade"],
    ["im", "google", "search service", "serviço de busca"],
    ["gr", "sans", "storage area network", "rede de área de armazenamento"],
    ["gr", "tree", "hierarchy", "hierarquia"],
    ["gr", "info", "idea", "ideia"],
    ["gr", "zoom", "Zoom", "Zoom"],
    ["gr", "time", "signal measurement", "medição de sinal"],
    ["gr", "toast", "breakfast", "café da manhã"],
    ["cg", "ghost", "Ghost", "Ghost"],
    ["cg", "ghost-character", "Halloween", "Dia das Bruxas"],
    ["cg", "unfold", "Unfold", "Unfold"],
    ["cg", "format-strike", "strikethrough", "tachado"],
    ["cg", "arrow-left", "go back", "voltar"],
    ["cg", "toggle-off", "disabled setting", "configuração desativada"],
    ["io", "ios-restaurant", "reservation", "reserva"],
    ["io", "md-pin", "point of interest", "ponto de interesse"],
    ["io", "ios-american-football", "NFL", "futebol americano"],
    ["io", "md-football", "soccer", "futebol"],
    ["io", "ios-appstore", "Apple App Store logo", "logotipo Apple App Store"],
    ["io", "logo-github", "GitHub logo", "logotipo GitHub"],
    ["io", "logo-usd", "USD", "USD"],
    ["io", "logo-closed-captioning", "subtitles", "subtítulos"],
    ["io", "md-notifications-off", "do not disturb", "não perturbe"],
    ["io", "ios-pulse", "vital signs", "sinais vitais"],
    ["md", "arrow-back", "arrow", "seta"],
    ["md", "cloud", "cloud", "nuvem"],
    ["md", "folder", "folder", "pasta"],
    ["md", "home", "home", "casa"],
    ["md", "search", "search", "buscar"],
    ["md", "phone", "phone", "telefone"],
    ["md", "settings", "settings", "configurações"],
    ["md", "delete", "delete", "excluir"],
    ["md", "account-circle", "account", "conta"],
    ["md", "insert-drive-file", "insert", "inserir"],
    ["bi", "arrow-to-left", "arrow", "seta"],
    ["bi", "cloud", "cloud", "nuvem"],
    ["bi", "code", "code", "código"],
    ["bi", "file", "file", "arquivo"],
    ["bi", "search", "search", "buscar"],
    ["bi", "home", "home", "casa"],
    ["bi", "heart", "heart", "coração"],
    ["bi", "phone", "phone", "telefone"],
    ["bi", "folder", "folder", "pasta"],
    ["bi", "trash", "trash", "lixeira"],
    ["lia", "arrow-left", "arrow", "seta"],
    ["lia", "cloud", "cloud", "nuvem"],
    ["lia", "code", "code", "código"],
    ["lia", "file", "file", "arquivo"],
    ["lia", "search", "search", "buscar"],
    ["lia", "home", "home", "casa"],
    ["lia", "heart", "heart", "coração"],
    ["lia", "phone", "phone", "telefone"],
    ["lia", "folder", "folder", "pasta"],
    ["lia", "trash", "trash", "lixeira"],
    ["fa", "arrow-left", "arrow", "seta"],
    ["fa", "cloud", "cloud", "nuvem"],
    ["fa", "code", "code", "código"],
    ["fa", "file-pdf", "file", "arquivo"],
    ["fa", "search", "search", "buscar"],
    ["fa", "home", "home", "casa"],
    ["fa", "heart", "heart", "coração"],
    ["fa", "phone", "phone", "telefone"],
    ["fa", "folder", "folder", "pasta"],
    ["fa", "trash", "trash", "lixeira"],
    ["fa", "wifi", "wifi", "wifi"],
    ["io5", "add", "add", "adicionar"],
    ["io5", "arrow-back", "arrow", "seta"],
    ["io5", "notifications", "notifications", "notificações"],
    ["io5", "search", "search", "buscar"],
    ["io5", "document", "document", "documento"],
    ["io5", "logo-github", "brand logo", "logotipo"],
    ["io5", "restaurant", "restaurant", "restaurante"],
    ["io5", "terminal", "terminal", "terminal"],
    ["io5", "wifi", "wifi", "wifi"],
    ["io5", "people", "people", "pessoas"],
    ["rx", "activity-log", "audit trail", "trilha de auditoria"],
    ["rx", "avatar", "user profile", "perfil de usuário"],
    ["rx", "box-model", "CSS box model", "box model do CSS"],
    ["rx", "database", "backend", "backend"],
    ["rx", "server", "hosting", "hospedagem"],
    ["rx", "twitter-logo", "X", "X"],
    ["si", "github", "github", "github"],
    ["si", "react", "react", "react"],
    ["si", "typescript", "typescript", "typescript"],
    ["si", "python", "python", "python"],
    ["si", "docker", "docker", "docker"],
    ["si", "google", "google", "google"],
    ["si", "apple", "apple", "apple"],
    ["si", "slackware", "slackware", "slackware"],
    ["si", "stripe", "stripe", "stripe"],
    ["si", "figma", "figma", "figma"],
    ["ri", "arrow-left", "arrow", "seta"],
    ["ri", "cloud", "cloud", "nuvem"],
    ["ri", "folder", "folder", "pasta"],
    ["ri", "home", "home", "casa"],
    ["ri", "search", "search", "buscar"],
    ["ri", "phone", "phone", "telefone"],
    ["ri", "settings", "settings", "configurações"],
    ["ri", "delete-bin", "delete", "excluir"],
    ["ri", "account-circle", "account", "conta"],
    ["ri", "calendar", "calendar", "calendário"],
    ["pi", "arrow-left", "arrow", "seta"],
    ["pi", "cloud", "cloud", "nuvem"],
    ["pi", "folder", "folder", "pasta"],
    ["pi", "house", "home", "casa"],
    ["pi", "magnifying-glass", "search", "buscar"],
    ["pi", "phone", "phone", "telefone"],
    ["pi", "gear", "settings", "configurações"],
    ["pi", "trash", "trash", "lixeira"],
    ["pi", "user", "user", "usuário"],
    ["pi", "calendar", "calendar", "calendário"],
    ["pi", "bell", "notification", "notificação"],
    ["gi", "arrow-cluster", "arrow", "seta"],
    ["gi", "cloud-download", "cloud", "nuvem"],
    ["gi", "database", "database", "banco de dados"],
    ["gi", "house", "home", "casa"],
    ["gi", "magnifying-glass", "search", "buscar"],
    ["gi", "phone", "phone", "telefone"],
    ["gi", "trash-can", "trash", "lixeira"],
    ["gi", "compass", "compass", "bússola"],
    ["gi", "open-folder", "folder", "pasta"],
    ["gi", "share", "share", "compartilhar"],
    ["fa6", "arrow-left", "arrow", "seta"],
    ["fa6", "cloud", "cloud", "nuvem"],
    ["fa6", "code", "code", "código"],
    ["fa6", "file", "file", "arquivo"],
    ["fa6", "magnifying-glass", "search", "buscar"],
    ["fa6", "house", "home", "casa"],
    ["fa6", "heart", "heart", "coração"],
    ["fa6", "phone", "phone", "telefone"],
    ["fa6", "folder", "folder", "pasta"],
    ["fa6", "trash", "trash", "lixeira"],
    ["bs", "arrow-left", "arrow", "seta"],
    ["bs", "cloud", "cloud", "nuvem"],
    ["bs", "code", "code", "código"],
    ["bs", "file", "file", "arquivo"],
    ["bs", "search", "search", "buscar"],
    ["bs", "house", "home", "casa"],
    ["bs", "heart", "heart", "coração"],
    ["bs", "phone", "phone", "telefone"],
    ["bs", "folder", "folder", "pasta"],
    ["bs", "trash", "trash", "lixeira"],
    ["ai", "account-book", "accounting", "contabilidade"],
    ["ai", "arrow-left", "previous", "anterior"],
    ["ai", "bell", "notification", "notificação"],
    ["ai", "shopping-cart", "checkout", "checkout"],
    ["ai", "file-pdf", "PDF", "PDF"],
    ["ai", "code", "terminal", "terminal"],
    ["ai", "search", "lookup", "buscar"],
    ["ai", "cloud-sync", "sync", "sincronizar"],
    ["ai", "twotone-file-excel", "spreadsheet", "planilha"],
    ["ai", "user-add", "invite", "convidar"],
    ["ai", "wechat", "WeChat", "WeChat"],
    ["tb", "arrow-left", "arrow", "seta"],
    ["tb", "cloud", "cloud", "nuvem"],
    ["tb", "folder", "folder", "pasta"],
    ["tb", "home", "home", "casa"],
    ["tb", "search", "search", "buscar"],
    ["tb", "phone", "phone", "telefone"],
    ["tb", "settings", "settings", "configurações"],
    ["tb", "trash", "trash", "lixeira"],
    ["tb", "user", "user", "usuário"],
    ["tb", "calendar", "calendar", "calendário"]
  ];

  test.each(queries)(
    "%s/%s supports its reviewed English and Portuguese intents",
    (id, familyId, en, pt) => {
      const source = loadContextSource(id)!;
      const family = source.families.find((entry) => entry.familyId === familyId)!;
      expect([...family.aliases.en, ...family.searchTerms.en]).toContain(en);
      expect([...family.aliases["pt-BR"], ...family.searchTerms["pt-BR"]]).toContain(pt);
    }
  );

  test.each([
    ["vsc", "git-stash-apply", "remove stash"],
    ["vsc", "git-stash-pop", "keep stash entry"],
    ["vsc", "copilot-error", "Copilot success"],
    ["rc", "rocket-icon", "rocket launch"],
    ["tfi", "support", "lifebuoy"],
    ["tfi", "cup", "coffee cup"],
    ["im", "power", "power button"],
    ["im", "tree", "forest"],
    ["gr", "sans", "sans-serif font"],
    ["gr", "zoom", "magnifying glass"],
    ["cg", "ghost", "ghost character"],
    ["cg", "unfold", "unfold code"],
    ["io", "ios-american-football", "soccer ball"],
    ["io", "md-football", "American football"],
    ["io", "md-pin", "pushpin"],
    ["io", "ios-water", "map pin"],
    ["rx", "database", "server hardware"],
    ["rx", "server", "database"],
    ["rx", "stop", "warning sign"],
    ["ai", "arrow-left", "right arrow"],
    ["ai", "arrow-right", "left arrow"],
    ["ai", "check", "x mark"],
    ["ai", "twotone-file-pdf", "Excel"],
    ["ai", "user-delete", "add user"],
    ["hi2", "arrow-left", "move right"],
    ["hi2", "arrow-right", "move left"],
    ["hi2", "x-mark", "check mark"],
    ["hi2", "face-smile", "sad face"]
  ])("%s/%s keeps misleading intent %s out of positive metadata", (id, familyId, negative) => {
    const family = loadContextSource(id)!.families.find((entry) => entry.familyId === familyId)!;
    expect(family.negativeTerms.en).toContain(negative);
    expect([...family.aliases.en, ...family.searchTerms.en]).not.toContain(negative);
  });
});
